#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Clase1_4to_24_04")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Updatetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Deletetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    partial void Inserttbl_usuario_imagen(tbl_usuario_imagen instance);
    partial void Updatetbl_usuario_imagen(tbl_usuario_imagen instance);
    partial void Deletetbl_usuario_imagen(tbl_usuario_imagen instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_producto_imagen(tbl_producto_imagen instance);
    partial void Updatetbl_producto_imagen(tbl_producto_imagen instance);
    partial void Deletetbl_producto_imagen(tbl_producto_imagen instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Clase1_4to_24_04ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_tipo_usuario> tbl_tipo_usuario
		{
			get
			{
				return this.GetTable<tbl_tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario_imagen> tbl_usuario_imagen
		{
			get
			{
				return this.GetTable<tbl_usuario_imagen>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto_imagen> tbl_producto_imagen
		{
			get
			{
				return this.GetTable<tbl_producto_imagen>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.desencriptacon", IsComposable=true)]
		public string desencriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary clave)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.encriptacon", IsComposable=true)]
		public System.Data.Linq.Binary encriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clave)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReiniciarIntentosDiarios")]
		public int sp_ReiniciarIntentosDiarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarProveedor")]
		public int sp_EliminarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prov_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prov_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ImportarProveedor")]
		public int sp_ImportarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prov_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prov_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> prov_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prov_id, prov_nombre, prov_estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReiniciarIntentosDiarios")]
		public int sp_ReiniciarIntentosDiarios1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ImportarProducto")]
		public int sp_ImportarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pro_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pro_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pro_cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> pro_precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> pro_estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prov_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prov_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pro_id, pro_nombre, pro_cantidad, pro_precio, pro_estado, prov_id, prov_nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ImportarProductoImagen")]
		public int sp_ImportarProductoImagen([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pimg_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pro_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string pimg_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string pimg_ruta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> pimg_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pimg_id, pro_id, pimg_nombre, pimg_ruta, pimg_estado);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_usuario")]
	public partial class tbl_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public tbl_tipo_usuario()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50)")]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_usuario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombres;
		
		private string _usu_apellidos;
		
		private string _usu_direccion;
		
		private string _usu_celular;
		
		private string _usu_correo;
		
		private System.Nullable<System.DateTime> _usu_fecha_creacion;
		
		private System.Nullable<System.DateTime> _usu_fecha_cumple;
		
		private string _usu_nick;
		
		private System.Data.Linq.Binary _usu_contrasenia;
		
		private System.Nullable<int> _usu_intentos;
		
		private string _usu_codigo_OPT;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _tusu_id;
		
		private System.Nullable<System.DateTime> _usu_fecha_ultimo_intento;
		
		private EntitySet<tbl_usuario_imagen> _tbl_usuario_imagen;
		
		private EntityRef<tbl_tipo_usuario> _tbl_tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_creacionChanged();
    partial void Onusu_fecha_cumpleChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_cumpleChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_contraseniaChanging(System.Data.Linq.Binary value);
    partial void Onusu_contraseniaChanged();
    partial void Onusu_intentosChanging(System.Nullable<int> value);
    partial void Onusu_intentosChanged();
    partial void Onusu_codigo_OPTChanging(string value);
    partial void Onusu_codigo_OPTChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(System.Nullable<int> value);
    partial void Ontusu_idChanged();
    partial void Onusu_fecha_ultimo_intentoChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_ultimo_intentoChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_usuario_imagen = new EntitySet<tbl_usuario_imagen>(new Action<tbl_usuario_imagen>(this.attach_tbl_usuario_imagen), new Action<tbl_usuario_imagen>(this.detach_tbl_usuario_imagen));
			this._tbl_tipo_usuario = default(EntityRef<tbl_tipo_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="VarChar(50)")]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(50)")]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(50)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(10)")]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(150)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_creacion
		{
			get
			{
				return this._usu_fecha_creacion;
			}
			set
			{
				if ((this._usu_fecha_creacion != value))
				{
					this.Onusu_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_creacion = value;
					this.SendPropertyChanged("usu_fecha_creacion");
					this.Onusu_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_cumple", DbType="Date")]
		public System.Nullable<System.DateTime> usu_fecha_cumple
		{
			get
			{
				return this._usu_fecha_cumple;
			}
			set
			{
				if ((this._usu_fecha_cumple != value))
				{
					this.Onusu_fecha_cumpleChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_cumple = value;
					this.SendPropertyChanged("usu_fecha_cumple");
					this.Onusu_fecha_cumpleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(50)")]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contrasenia", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_contrasenia
		{
			get
			{
				return this._usu_contrasenia;
			}
			set
			{
				if ((this._usu_contrasenia != value))
				{
					this.Onusu_contraseniaChanging(value);
					this.SendPropertyChanging();
					this._usu_contrasenia = value;
					this.SendPropertyChanged("usu_contrasenia");
					this.Onusu_contraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_intentos", DbType="Int")]
		public System.Nullable<int> usu_intentos
		{
			get
			{
				return this._usu_intentos;
			}
			set
			{
				if ((this._usu_intentos != value))
				{
					this.Onusu_intentosChanging(value);
					this.SendPropertyChanging();
					this._usu_intentos = value;
					this.SendPropertyChanged("usu_intentos");
					this.Onusu_intentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo_OPT", DbType="VarChar(10)")]
		public string usu_codigo_OPT
		{
			get
			{
				return this._usu_codigo_OPT;
			}
			set
			{
				if ((this._usu_codigo_OPT != value))
				{
					this.Onusu_codigo_OPTChanging(value);
					this.SendPropertyChanging();
					this._usu_codigo_OPT = value;
					this.SendPropertyChanged("usu_codigo_OPT");
					this.Onusu_codigo_OPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int")]
		public System.Nullable<int> tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._tbl_tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_ultimo_intento", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_ultimo_intento
		{
			get
			{
				return this._usu_fecha_ultimo_intento;
			}
			set
			{
				if ((this._usu_fecha_ultimo_intento != value))
				{
					this.Onusu_fecha_ultimo_intentoChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_ultimo_intento = value;
					this.SendPropertyChanged("usu_fecha_ultimo_intento");
					this.Onusu_fecha_ultimo_intentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_imagen", Storage="_tbl_usuario_imagen", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_usuario_imagen> tbl_usuario_imagen
		{
			get
			{
				return this._tbl_usuario_imagen;
			}
			set
			{
				this._tbl_usuario_imagen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_tipo_usuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public tbl_tipo_usuario tbl_tipo_usuario
		{
			get
			{
				return this._tbl_tipo_usuario.Entity;
			}
			set
			{
				tbl_tipo_usuario previousValue = this._tbl_tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_usuario.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tipo_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario_imagen(tbl_usuario_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_usuario_imagen(tbl_usuario_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario_imagen")]
	public partial class tbl_usuario_imagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uimg_id;
		
		private int _usu_id;
		
		private string _uimg_nombre;
		
		private string _uimg_tipo;
		
		private System.Data.Linq.Binary _uimg_data;
		
		private System.Nullable<System.DateTime> _uimg_fecha_creacion;
		
		private System.Nullable<char> _uimg_estado;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuimg_idChanging(int value);
    partial void Onuimg_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onuimg_nombreChanging(string value);
    partial void Onuimg_nombreChanged();
    partial void Onuimg_tipoChanging(string value);
    partial void Onuimg_tipoChanged();
    partial void Onuimg_dataChanging(System.Data.Linq.Binary value);
    partial void Onuimg_dataChanged();
    partial void Onuimg_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onuimg_fecha_creacionChanged();
    partial void Onuimg_estadoChanging(System.Nullable<char> value);
    partial void Onuimg_estadoChanged();
    #endregion
		
		public tbl_usuario_imagen()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uimg_id
		{
			get
			{
				return this._uimg_id;
			}
			set
			{
				if ((this._uimg_id != value))
				{
					this.Onuimg_idChanging(value);
					this.SendPropertyChanging();
					this._uimg_id = value;
					this.SendPropertyChanged("uimg_id");
					this.Onuimg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_nombre", DbType="VarChar(150)")]
		public string uimg_nombre
		{
			get
			{
				return this._uimg_nombre;
			}
			set
			{
				if ((this._uimg_nombre != value))
				{
					this.Onuimg_nombreChanging(value);
					this.SendPropertyChanging();
					this._uimg_nombre = value;
					this.SendPropertyChanged("uimg_nombre");
					this.Onuimg_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_tipo", DbType="VarChar(50)")]
		public string uimg_tipo
		{
			get
			{
				return this._uimg_tipo;
			}
			set
			{
				if ((this._uimg_tipo != value))
				{
					this.Onuimg_tipoChanging(value);
					this.SendPropertyChanging();
					this._uimg_tipo = value;
					this.SendPropertyChanged("uimg_tipo");
					this.Onuimg_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_data", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary uimg_data
		{
			get
			{
				return this._uimg_data;
			}
			set
			{
				if ((this._uimg_data != value))
				{
					this.Onuimg_dataChanging(value);
					this.SendPropertyChanging();
					this._uimg_data = value;
					this.SendPropertyChanged("uimg_data");
					this.Onuimg_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> uimg_fecha_creacion
		{
			get
			{
				return this._uimg_fecha_creacion;
			}
			set
			{
				if ((this._uimg_fecha_creacion != value))
				{
					this.Onuimg_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._uimg_fecha_creacion = value;
					this.SendPropertyChanged("uimg_fecha_creacion");
					this.Onuimg_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uimg_estado", DbType="Char(1)")]
		public System.Nullable<char> uimg_estado
		{
			get
			{
				return this._uimg_estado;
			}
			set
			{
				if ((this._uimg_estado != value))
				{
					this.Onuimg_estadoChanging(value);
					this.SendPropertyChanging();
					this._uimg_estado = value;
					this.SendPropertyChanged("uimg_estado");
					this.Onuimg_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_imagen", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_usuario_imagen.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario_imagen.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio;
		
		private char _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private EntitySet<tbl_producto_imagen> _tbl_producto_imagen;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(System.Nullable<decimal> value);
    partial void Onpro_precioChanged();
    partial void Onpro_estadoChanging(char value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_producto_imagen = new EntitySet<tbl_producto_imagen>(new Action<tbl_producto_imagen>(this.attach_tbl_producto_imagen), new Action<tbl_producto_imagen>(this.detach_tbl_producto_imagen));
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1) NOT NULL")]
		public char pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_imagen", Storage="_tbl_producto_imagen", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_producto_imagen> tbl_producto_imagen
		{
			get
			{
				return this._tbl_producto_imagen;
			}
			set
			{
				this._tbl_producto_imagen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto_imagen(tbl_producto_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_producto_imagen(tbl_producto_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto_imagen")]
	public partial class tbl_producto_imagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pimg_id;
		
		private int _pro_id;
		
		private string _pimg_nombre;
		
		private string _pimg_ruta;
		
		private System.DateTime _pimg_fecha_creacion;
		
		private char _pimg_estado;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpimg_idChanging(int value);
    partial void Onpimg_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpimg_nombreChanging(string value);
    partial void Onpimg_nombreChanged();
    partial void Onpimg_rutaChanging(string value);
    partial void Onpimg_rutaChanged();
    partial void Onpimg_fecha_creacionChanging(System.DateTime value);
    partial void Onpimg_fecha_creacionChanged();
    partial void Onpimg_estadoChanging(char value);
    partial void Onpimg_estadoChanged();
    #endregion
		
		public tbl_producto_imagen()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimg_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pimg_id
		{
			get
			{
				return this._pimg_id;
			}
			set
			{
				if ((this._pimg_id != value))
				{
					this.Onpimg_idChanging(value);
					this.SendPropertyChanging();
					this._pimg_id = value;
					this.SendPropertyChanged("pimg_id");
					this.Onpimg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimg_nombre", DbType="VarChar(150)")]
		public string pimg_nombre
		{
			get
			{
				return this._pimg_nombre;
			}
			set
			{
				if ((this._pimg_nombre != value))
				{
					this.Onpimg_nombreChanging(value);
					this.SendPropertyChanging();
					this._pimg_nombre = value;
					this.SendPropertyChanged("pimg_nombre");
					this.Onpimg_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimg_ruta", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string pimg_ruta
		{
			get
			{
				return this._pimg_ruta;
			}
			set
			{
				if ((this._pimg_ruta != value))
				{
					this.Onpimg_rutaChanging(value);
					this.SendPropertyChanging();
					this._pimg_ruta = value;
					this.SendPropertyChanged("pimg_ruta");
					this.Onpimg_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimg_fecha_creacion", DbType="DateTime NOT NULL")]
		public System.DateTime pimg_fecha_creacion
		{
			get
			{
				return this._pimg_fecha_creacion;
			}
			set
			{
				if ((this._pimg_fecha_creacion != value))
				{
					this.Onpimg_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._pimg_fecha_creacion = value;
					this.SendPropertyChanged("pimg_fecha_creacion");
					this.Onpimg_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimg_estado", DbType="Char(1) NOT NULL")]
		public char pimg_estado
		{
			get
			{
				return this._pimg_estado;
			}
			set
			{
				if ((this._pimg_estado != value))
				{
					this.Onpimg_estadoChanging(value);
					this.SendPropertyChanging();
					this._pimg_estado = value;
					this.SendPropertyChanged("pimg_estado");
					this.Onpimg_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_imagen", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_producto_imagen.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_producto_imagen.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private char _prov_estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(char value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1) NOT NULL")]
		public char prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
}
#pragma warning restore 1591
